### ISSUE TITLE
pmda.density not compatible to MDA 2.0.0

### ISSUE THREAD

**Issue by appassionate** [MDAnalysis/pmda#154]
### Expected behaviour
successfully import pmda.density.DensityAnalysis

### Actual behaviour
Error, cant import density in pmda. (MDA edition = 2.0.0)

### Code to reproduce the behaviour

``` python

from pmda.density import * #or other imports?
ImportError: cannot import name '_set_user_grid' from 'MDAnalysis.analysis.density' 

```

### Currently version of MDAnalysis:
mda.__version__ =2.0.0
pmda.__version__= 0.3.0
dask.__version__ = 2021.05.0

**Comment by orbeckst** [comment]
Yes, PMDA needs to be made to work with MDA 2.0.0 #148
